// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxro1wmf8jDaTr3EmvnSiDtZG0XBDZAUM',
    appId: '1:140205371500:android:be201b5ad1ec54289ae849',
    messagingSenderId: '140205371500',
    projectId: 'my-chat-30a43',
    storageBucket: 'my-chat-30a43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UvH1uq6D6WHlhPYG_65H1wP_twm5o8E',
    appId: '1:140205371500:ios:29ea0c60e0ca5a2c9ae849',
    messagingSenderId: '140205371500',
    projectId: 'my-chat-30a43',
    storageBucket: 'my-chat-30a43.appspot.com',
    androidClientId: '140205371500-mn8446p9pa6097hothd2j49jsaqf4kbp.apps.googleusercontent.com',
    iosClientId: '140205371500-mpc8qv3gkfau4tk4rgrpoqdvl25kguhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.myChat',
  );
}
